/*
    Attention: This file is generated by "reaux-cli", do not modify
*/
import { StateView } from 'reaux-dom';

import { State as MainState } from 'src/modules/main/type';

export interface AllState extends StateView {
  main: MainState;
}
